# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tofserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tofserver.proto',
  package='payload',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftofserver.proto\x12\x07payload\"\x1b\n\tCamStatus\x12\x0e\n\x06status\x18\x0f \x01(\t\"\x1c\n\nInitStatus\x12\x0e\n\x06status\x18\x0f \x01(\t\"\"\n\rClientRequest\x12\x11\n\tfunc_name\x18\x14 \x01(\t\"\x1a\n\x05\x46rame\x12\x11\n\x05\x61rray\x18\x32 \x03(\x01\x42\x02\x10\x01\x32\xbf\x01\n\tTofServer\x12\x39\n\tGetStatus\x12\x16.payload.ClientRequest\x1a\x12.payload.CamStatus\"\x00\x12\x41\n\x10InitializeCamera\x12\x16.payload.ClientRequest\x1a\x13.payload.InitStatus\"\x00\x12\x34\n\x08GetFrame\x12\x16.payload.ClientRequest\x1a\x0e.payload.Frame\"\x00\x62\x06proto3'
)




_CAMSTATUS = _descriptor.Descriptor(
  name='CamStatus',
  full_name='payload.CamStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='payload.CamStatus.status', index=0,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_INITSTATUS = _descriptor.Descriptor(
  name='InitStatus',
  full_name='payload.InitStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='payload.InitStatus.status', index=0,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)


_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='payload.ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='func_name', full_name='payload.ClientRequest.func_name', index=0,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=121,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='payload.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='payload.Frame.array', index=0,
      number=50, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['CamStatus'] = _CAMSTATUS
DESCRIPTOR.message_types_by_name['InitStatus'] = _INITSTATUS
DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CamStatus = _reflection.GeneratedProtocolMessageType('CamStatus', (_message.Message,), {
  'DESCRIPTOR' : _CAMSTATUS,
  '__module__' : 'tofserver_pb2'
  # @@protoc_insertion_point(class_scope:payload.CamStatus)
  })
_sym_db.RegisterMessage(CamStatus)

InitStatus = _reflection.GeneratedProtocolMessageType('InitStatus', (_message.Message,), {
  'DESCRIPTOR' : _INITSTATUS,
  '__module__' : 'tofserver_pb2'
  # @@protoc_insertion_point(class_scope:payload.InitStatus)
  })
_sym_db.RegisterMessage(InitStatus)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'tofserver_pb2'
  # @@protoc_insertion_point(class_scope:payload.ClientRequest)
  })
_sym_db.RegisterMessage(ClientRequest)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'tofserver_pb2'
  # @@protoc_insertion_point(class_scope:payload.Frame)
  })
_sym_db.RegisterMessage(Frame)


_FRAME.fields_by_name['array']._options = None

_TOFSERVER = _descriptor.ServiceDescriptor(
  name='TofServer',
  full_name='payload.TofServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=343,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='payload.TofServer.GetStatus',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_CAMSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InitializeCamera',
    full_name='payload.TofServer.InitializeCamera',
    index=1,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_INITSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='payload.TofServer.GetFrame',
    index=2,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_FRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOFSERVER)

DESCRIPTOR.services_by_name['TofServer'] = _TOFSERVER

# @@protoc_insertion_point(module_scope)
